### ISSUE TITLE
Create Organization Repository Guidelines

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/f5devcentral.github.io#4]
This Github page will help outline expectations of repositories in the F5DevCentral Organization:
- required files
  - License 
  - Code of Conduct
  - Readme
  - Contributing
- documentation
- when repositories will be archived 
- public versus private repositories

I think we should base our initial guideline on the [Creative Commons guidelines](https://opensource.creativecommons.org/contributing-code/github-repo-guidelines/)

**Comment by adam-f5** [comment]
Repository Archived
